services:
  rdvbot:
    image: betagouv/rdvbot
    build: .
    environment:
      RDVBOT_URL: rdvbot:9292/
      RDVBOT_MATTERMOST_API_URL: http://mattermost:8065/api/v4/
    ports:
      - "9292:9292"
    volumes:
      - ".:/app"
  mattermost:
    image: mattermost/mattermost-preview
    environment:
      MM_SERVICESETTINGS_ALLOWEDUNTRUSTEDINTERNALCONNECTIONS: "rdvbot"
    ports:
      - "8065:8065"
    volumes:
      - ${MATTERMOST_CONFIG_PATH}:/mattermost/config:rw
      - ${MATTERMOST_DATA_PATH}:/mattermost/data:rw
      - ${MATTERMOST_LOGS_PATH}:/mattermost/logs:rw
      - ${MATTERMOST_PLUGINS_PATH}:/mattermost/plugins:rw
      - ${MATTERMOST_CLIENT_PLUGINS_PATH}:/mattermost/client/plugins:rw
      - ${MATTERMOST_BLEVE_INDEXES_PATH}:/mattermost/bleve-indexes:rw
